version: "3.4"
services:
  cache-tests:
    container_name: cache-tests
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    network_mode: host
    volumes:
      - /location_of_cache_tests/results_dir:/cache-tests/results:rw
