version: '3'

services:
  github-mirror-smart-http:
    build: .
    image: trafficserver/github-mirror-smart-http:latest
    container_name: github-mirror-smart-http
    restart: unless-stopped
    ports:
      - "127.0.0.1:9417:80"
    volumes:
      - /home/mirror:/usr/local/apache2/mirror:ro
      - /var/log/github-mirror-smart-http:/usr/local/apache2/logs
